version: "3.8"
services:
  frontend:
    build: ./routertutorial
    ports:
      - '3000:3000'
    volumes:
      - ./routertutorial:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./nodejs
    ports:
      - '5000:5000'
    volumes:
      - ./nodejs:/app
      - ./app/node_modules